CREATE TABLE `journal_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`setupId` varchar(64) NOT NULL,
	`symbol` varchar(20) NOT NULL,
	`assetClass` enum('STOCK','FOREX') NOT NULL,
	`setupType` enum('CALL','PUT','LONG','SHORT') NOT NULL,
	`quality` enum('PREMIUM','STRONG','DEVELOPING') NOT NULL,
	`pattern` varchar(120) NOT NULL,
	`timeframe` varchar(10) NOT NULL,
	`levels` json NOT NULL,
	`rrRatio` float NOT NULL,
	`confluences` json NOT NULL,
	`notes` text DEFAULT (''),
	`outcome` enum('WIN','LOSS','BREAKEVEN','PENDING') DEFAULT 'PENDING',
	`pnl` float,
	`tags` json NOT NULL,
	`sector` varchar(80),
	`ivRank` int,
	`session` varchar(60),
	`pushedAt` timestamp NOT NULL DEFAULT (now()),
	`entryDate` timestamp,
	`exitDate` timestamp,
	CONSTRAINT `journal_entries_id` PRIMARY KEY(`id`)
);
