export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  polygonApiKey: process.env.POLYGON_API_KEY ?? "",
  oandaApiKey: process.env.OANDA_API_KEY ?? "",
  oandaAccountId: process.env.OANDA_ACCOUNT_ID ?? "",
  oandaAccountType: process.env.OANDA_ACCOUNT_TYPE ?? "practice",
  tradierApiKey: process.env.TRADIER_ACCESS_TOKEN ?? "",
  tradierBaseUrl: process.env.TRADIER_BASE_URL ?? "https://api.tradier.com/v1",
};
